### Import libraries

In [1]:
import pandas as pd
import numpy as np

### Loading dataset

In [2]:
data=pd.read_excel(r"C:\Users\sujat\Downloads\Dry_Bean_Dataset.xlsx")
data

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0      28395    610.291       208.178117       173.888747      1.197191   
1      28734    638.018       200.524796       182.734419      1.097356   
2      29380    624.110       212.826130       175.931143      1.209713   
3      30008    645.884       210.557999       182.516516      1.153638   
4      30140    620.134       201.847882       190.279279      1.060798   
...      ...        ...              ...              ...           ...   
13606  42097    759.696       288.721612       185.944705      1.552728   
13607  42101    757.499       281.576392       190.713136      1.476439   
13608  42139    759.321       281.539928       191.187979      1.472582   
13609  42147    763.779       283.382636       190.275731      1.489326   
13610  42159    772.237       295.142741       182.204716      1.619841   

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0          0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1          0.411785       29172     191.272750  0.783968  0.984986   0.887034   
2          0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3          0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4          0.333680       30417     195.896503  0.773098  0.990893   0.984877   
...             ...         ...            ...       ...       ...        ...   
13606      0.765002       42508     231.515799  0.714574  0.990331   0.916603   
13607      0.735702       42494     231.526798  0.799943  0.990752   0.922015   
13608      0.734065       42569     231.631261  0.729932  0.989899   0.918424   
13609      0.741055       42667     231.653248  0.705389  0.987813   0.907906   
13610      0.786693       42600     231.686223  0.788962  0.989648   0.888380   

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  \
0         0.913358      0.007332      0.003147      0.834222      0.998724   
1         0.953861      0.006979      0.003564      0.909851      0.998430   
2         0.908774      0.007244      0.003048      0.825871      0.999066   
3         0.928329      0.007017      0.003215      0.861794      0.994199   
4         0.970516      0.006697      0.003665      0.941900      0.999166   
...            ...           ...           ...           ...           ...   
13606     0.801865      0.006858      0.001749      0.642988      0.998385   
13607     0.822252      0.006688      0.001886      0.676099      0.998219   
13608     0.822730      0.006681      0.001888      0.676884      0.996767   
13609     0.817457      0.006724      0.001852      0.668237      0.995222   
13610     0.784997      0.007001      0.001640      0.616221      0.998180   

          Class  
0         SEKER  
1         SEKER  
2         SEKER  
3         SEKER  
4         SEKER  
...         ...  
13606  DERMASON  
13607  DERMASON  
13608  DERMASON  
13609  DERMASON  
13610  DERMASON  

[13611 rows x 17 columns]

### Data Preprocessiong

In [3]:
data.isnull().sum()

Area               0
Perimeter          0
MajorAxisLength    0
MinorAxisLength    0
AspectRation       0
Eccentricity       0
ConvexArea         0
EquivDiameter      0
Extent             0
Solidity           0
roundness          0
Compactness        0
ShapeFactor1       0
ShapeFactor2       0
ShapeFactor3       0
ShapeFactor4       0
Class              0
dtype: int64

In [4]:
data["Class"].value_counts()

DERMASON    3546
SIRA        2636
SEKER       2027
HOROZ       1928
CALI        1630
BARBUNYA    1322
BOMBAY       522
Name: Class, dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
data["Class"]=l1.fit_transform(data["Class"])

In [6]:
data

Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
0      28395    610.291       208.178117       173.888747      1.197191   
1      28734    638.018       200.524796       182.734419      1.097356   
2      29380    624.110       212.826130       175.931143      1.209713   
3      30008    645.884       210.557999       182.516516      1.153638   
4      30140    620.134       201.847882       190.279279      1.060798   
...      ...        ...              ...              ...           ...   
13606  42097    759.696       288.721612       185.944705      1.552728   
13607  42101    757.499       281.576392       190.713136      1.476439   
13608  42139    759.321       281.539928       191.187979      1.472582   
13609  42147    763.779       283.382636       190.275731      1.489326   
13610  42159    772.237       295.142741       182.204716      1.619841   

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
0          0.549812       28715     190.141097  0.763923  0.988856   0.958027   
1          0.411785       29172     191.272750  0.783968  0.984986   0.887034   
2          0.562727       29690     193.410904  0.778113  0.989559   0.947849   
3          0.498616       30724     195.467062  0.782681  0.976696   0.903936   
4          0.333680       30417     195.896503  0.773098  0.990893   0.984877   
...             ...         ...            ...       ...       ...        ...   
13606      0.765002       42508     231.515799  0.714574  0.990331   0.916603   
13607      0.735702       42494     231.526798  0.799943  0.990752   0.922015   
13608      0.734065       42569     231.631261  0.729932  0.989899   0.918424   
13609      0.741055       42667     231.653248  0.705389  0.987813   0.907906   
13610      0.786693       42600     231.686223  0.788962  0.989648   0.888380   

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  \
0         0.913358      0.007332      0.003147      0.834222      0.998724   
1         0.953861      0.006979      0.003564      0.909851      0.998430   
2         0.908774      0.007244      0.003048      0.825871      0.999066   
3         0.928329      0.007017      0.003215      0.861794      0.994199   
4         0.970516      0.006697      0.003665      0.941900      0.999166   
...            ...           ...           ...           ...           ...   
13606     0.801865      0.006858      0.001749      0.642988      0.998385   
13607     0.822252      0.006688      0.001886      0.676099      0.998219   
13608     0.822730      0.006681      0.001888      0.676884      0.996767   
13609     0.817457      0.006724      0.001852      0.668237      0.995222   
13610     0.784997      0.007001      0.001640      0.616221      0.998180   

       Class  
0          5  
1          5  
2          5  
3          5  
4          5  
...      ...  
13606      3  
13607      3  
13608      3  
13609      3  
13610      3  

[13611 rows x 17 columns]

In [7]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

## Standardized data

In [8]:
from sklearn.preprocessing import StandardScaler
s1=StandardScaler()
s2=s1.fit_transform(x)
s2

array([[-0.84074853, -1.1433189 , -1.30659814, ...,  2.40217287,
         1.92572347,  0.83837103],
       [-0.82918764, -1.01392388, -1.39591111, ...,  3.10089314,
         2.68970162,  0.77113842],
       [-0.80715717, -1.07882906, -1.25235661, ...,  2.23509147,
         1.84135576,  0.91675514],
       ...,
       [-0.37203825, -0.44783294, -0.45047814, ...,  0.28920441,
         0.33632829,  0.39025114],
       [-0.37176543, -0.42702856, -0.42897404, ...,  0.22837538,
         0.2489734 ,  0.03644001],
       [-0.37135619, -0.38755718, -0.2917356 , ..., -0.12777587,
        -0.2764814 ,  0.71371948]])

In [9]:
data1=pd.DataFrame(s2)
data1

0         1         2         3         4         5         6   \
0     -0.840749 -1.143319 -1.306598 -0.631153 -1.565053 -2.185720 -0.841451   
1     -0.829188 -1.013924 -1.395911 -0.434445 -1.969784 -3.686040 -0.826102   
2     -0.807157 -1.078829 -1.252357 -0.585735 -1.514291 -2.045336 -0.808704   
3     -0.785741 -0.977215 -1.278825 -0.439290 -1.741618 -2.742211 -0.773975   
4     -0.781239 -1.097384 -1.380471 -0.266663 -2.117993 -4.535028 -0.784286   
...         ...       ...       ...       ...       ...       ...       ...   
13606 -0.373471 -0.446083 -0.366669 -0.363055 -0.123703  0.153343 -0.378191   
13607 -0.373334 -0.456336 -0.450053 -0.257015 -0.432979 -0.165141 -0.378662   
13608 -0.372038 -0.447833 -0.450478 -0.246456 -0.448618 -0.182940 -0.376143   
13609 -0.371765 -0.427029 -0.428974 -0.266742 -0.380735 -0.106960 -0.372851   
13610 -0.371356 -0.387557 -0.291736 -0.446224  0.148374  0.389116 -0.375101   

             7         8         9         10        11        12        13  \
0     -1.063341  0.289087  0.367613  1.423867  1.839116  0.680786  2.402173   
1     -1.044217  0.697477 -0.462907  0.231054  2.495449  0.367967  3.100893   
2     -1.008084  0.578195  0.518417  1.252865  1.764843  0.603129  2.235091   
3     -0.973337  0.671260 -2.241767  0.515049  2.081715  0.401718  2.515075   
4     -0.966080  0.476020  0.804772  1.874992  2.765330  0.118268  3.270983   
...         ...       ...       ...       ...       ...       ...       ...   
13606 -0.364148 -0.716284  0.684173  0.727872  0.032433  0.261425  0.055630   
13607 -0.363962  1.022933  0.774384  0.818807  0.362794  0.110384  0.285117   
13608 -0.362197 -0.403392  0.591370  0.758468  0.370533  0.104269  0.289204   
13609 -0.361825 -0.903414  0.143717  0.581753  0.285098  0.141906  0.228375   
13610 -0.361268  0.799227  0.537539  0.253681 -0.240904  0.387512 -0.127776   

             14        15  
0      1.925723  0.838371  
1      2.689702  0.771138  
2      1.841356  0.916755  
3      2.204250 -0.197985  
4      3.013462  0.939640  
...         ...       ...  
13606 -0.006086  0.760813  
13607  0.328393  0.722659  
13608  0.336328  0.390251  
13609  0.248973  0.036440  
13610 -0.276481  0.713719  

[13611 rows x 16 columns]

#### Data Balancing

In [10]:
from imblearn.over_sampling import RandomOverSampler
r1=RandomOverSampler()
x_data,y_data=r1.fit_resample(x,y)

In [11]:
from collections import Counter
print(Counter(y_data))

Counter({5: 3546, 0: 3546, 1: 3546, 2: 3546, 4: 3546, 6: 3546, 3: 3546})


### train-test-split

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.2,random_state=0)

### RandomForest

 #### What is Random Forest model ?
#### Random Forest is a popular machine learning algorithm that belongs to the supervised learning technique.
#### It can be used for both Classification and Regression problems in ML.
#### It is based on the concept of ensemble learning, which is a process of combining multiple classifiers to
#### solve a complex problem and to improve the performance of the model

#### Assumptions:
#### 1) There should be some actual values in the feature variable of the dataset so that the classifier can
#### predict accurate results rather than a guessed result.
#### 2) The predictions from each tree must have very low correlations.
#### Advantages :
#### 1) Random Forest is capable of performing both Classification and Regression tasks.
#### 2) It is capable of handling large datasets with high dimensionality.
#### 3) It enhances the accuracy of the model and prevents the overfitting issue.
#### Disadvantages :
#### Although random forest can be used for both classification and regression tasks, it is not more suitable for
#### Regression tasks. Python Implementation of Random Forest Algorithm

### What is Ensemble Techniques ?
#### Ensemble methods are techniques that create multiple models and then combine them to produce
#### improved results. Ensemble methods usually produces more accurate solutions than a single model would.

In [13]:
from sklearn.ensemble import RandomForestClassifier
rd1=RandomForestClassifier(n_estimators=10,criterion="entropy",max_depth=5,random_state=11)
rd1.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=5, n_estimators=10,
                       random_state=11)

In [14]:
y_pred=rd1.predict(x_test)
y_pred

array([1, 3, 6, ..., 3, 6, 0])

In [15]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_pred,y_test)*100
print(round(acc))

91


### Using StratifiedKFoldClassifier

In [16]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=5,shuffle=True, random_state=21)
skf.get_n_splits(x_data,y_data)
print(skf)

StratifiedKFold(n_splits=5, random_state=21, shuffle=True)


In [17]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

In [18]:
for train_data,test_data in skf.split(x_data,y_data):
  x_train,x_test=x_data[train_data],x_data[test_data]
  y_train,y_test=y_data[train_data],y_data[test_data]
  rd1.fit(x_train,y_train)
  scores=cross_val_score(rd1,x_train,y_train,cv=skf)
  y_pred=cross_val_predict(rd1,x_test,y_test)

  print("Checking y_test Balancing.......:",Counter(y_test))
  print(y_pred)
  print(scores)
  print(np.mean(scores)*100)

Checking y_test Balancing.......: Counter({5: 710, 6: 710, 0: 709, 1: 709, 2: 709, 4: 709, 3: 709})
[3 5 3 ... 6 6 6]
[0.92019134 0.90936556 0.91513473 0.9148829  0.91085369]
91.40856430673236
Checking y_test Balancing.......: Counter({0: 710, 3: 710, 5: 709, 1: 709, 2: 709, 4: 709, 6: 709})
[5 5 5 ... 6 6 6]
[0.91490433 0.91440081 0.90103249 0.90909091 0.91538655]
91.09630166136513
Checking y_test Balancing.......: Counter({1: 710, 5: 709, 0: 709, 2: 709, 4: 709, 6: 709, 3: 709})
[5 3 5 ... 5 6 6]
[0.91540785 0.91540785 0.89677744 0.91060186 0.91866029]
91.13710605312484
Checking y_test Balancing.......: Counter({2: 710, 5: 709, 0: 709, 1: 709, 4: 709, 6: 709, 3: 709})
[5 5 5 ... 6 6 6]
[0.91389728 0.90080564 0.90835851 0.91891211 0.89977336]
90.8349379933014
Checking y_test Balancing.......: Counter({4: 710, 5: 709, 0: 709, 1: 709, 2: 709, 6: 709, 3: 709})
[5 5 5 ... 6 6 6]
[0.91289023 0.9164149  0.9050856  0.89977336 0.91790481]
91.0413780370932
